



export const Tableau1 = [
    {
        id: 1,
        name: 'King Palace',
        description: "Situé à Grand-Popo, à 5 km du centre culturel Finno-Africain Villa Karo, l'Hotel Village Vacances Awale Plage propose un restaurant, un parking privé gratuit, un bar et un salon commun.",
        tarif: 20000,
        qte: 100,
        picture1: "images/home/pic1.jpg",
        city:"Parakou",
        type: "Professionnel",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic3.jpg",
        pic4: "images/home/pic4.jpg",
        // pic5: "images/home/user1/pic5.jpg",
        // pic6: "images/home/user1/pic6.jpg",
        // pic7: "images/home/user1/pic7.jpg",
        
    },
    {
        id: 2,
        name: 'Produit2',
        description: 'description produit',
        tarif: 15000,
        qte: 250,
        picture1: "images/home/pic5.jpeg",
        pic2: "images/home/pic6.jpg",
        pic3: "images/home/pic7.jpg",
        pic4: "images/home/pic8.jpg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 3,
        name: 'Produit3',
        description: 'description produit',
        tarif: 5000,
        qte: 23,
        picture1: "images/home/pic12.jpg",
        pic2: "images/home/pic10.jpg",
        pic3: "images/home/pic11.jpg",
        pic4: "images/home/pic12.jpg",
        city:"Parakou",
        type: "Professionnel",

    },
    {
        id: 4,
        name: 'Produit4',
        description: 'description produit',
        tarif: 43500,
        qte: 50,
        picture1: "images/home/pic11.jpg",
        pic2: "images/home/pic12.jpg",
        pic3: "images/home/pic10.jpg",
        pic4: "images/home/pic8.jpg",
        city:"Parakou",
        type: "Professionnel",

    },
    {
        id: 5,
        name: 'Produit5',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 6,
        name: 'Produit6',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 7,
        name: 'Produit7',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 8,
        name: 'Produit8',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 9,
        name: 'Produit9',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 10,
        name: 'Produit10',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 11,
        name: 'Produit11',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 12,
        name: 'Produit12',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 13,
        name: 'Produit13',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 14,
        name: 'Produit14',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 15,
        name: 'Produit15',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 16,
        name: 'Produit16',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 17,
        name: 'Produit17',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 18,
        name: 'Produit18',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 19,
        name: 'Produit19',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 20,
        name: 'Produit20',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 21,
        name: 'Produit21',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 22,
        name: 'Produit22',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 23,
        name: 'Produit23',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 24,
        name: 'Produit24',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 25,
        name: 'Produit25',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 26,
        name: 'Produit26',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 27,
        name: 'Produit27',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 28,
        name: 'Produit28',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 29,
        name: 'Produit29',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 30,
        name: 'Produit30',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 31,
        name: 'Produit31',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 32,
        name: 'Produit32',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 33,
        name: 'Produit33',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 34,
        name: 'Produit34',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 35,
        name: 'Produit35',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 36,
        name: 'Produit36',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 37,
        name: 'Produit37',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 38,
        name: 'Produit38',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
    {
        id: 39,
        name: 'Produit39',
        description: 'description produit',
        tarif: 70500,
        qte: 10,
        picture1: "images/home/pic7.jpg",
        pic2: "images/home/pic2.jpg",
        pic3: "images/home/pic6.jpg",
        pic4: "images/home/pic5.jpeg",
        city:"Parakou",
        type: "Particulier",

    },
   
   
  ];